#!/usr/bin/env bash

# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx

# Configure firewall to allow requests through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# Change permissions to allow creating files in this directory
sudo chmod -R 755 /var/www

# Create the index page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a webpage for error 404 (**Only one location block for 404.html**)
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# replacement code
string_for_replacement=$(cat <<EOF
server_name _;
add_header X-Served-By \$hostname;
rewrite ^\/redirect_me https:\/\/www.prosperabudu.tech permanent;
EOF
)
sudo sed -i "s/server_name _;/<span class="math-inline">string\_for\_replacement/" /etc/nginx/sites\-enabled/default
string\_for\_replacement\=</span>(cat <<EOF
listen 80 default_server;
error_page 404 /404.html;
location = /404.html {
    root /var/www/html;
    internal;
}
EOF
)
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart the web server after updating the settings
sudo service nginx restart
