#!/usr/bin/env bash

# Counter variable
counter=1

# Using while loop to iterate from 1 to 10
while [ $counter -le 10 ]; do
    # Checking for specific loop iterations
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    
    # Incrementing counter
    ((counter++))
done
